services:
  - type: web
    name: imf-gadget-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: imf-gadget-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: imf-gadget-db
    plan: free
    ipAllowList: []
